name: Main Release

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pages: write

    steps:
      - name: Assigning SIMPLE_REPOSITORY_NAME
        run: echo "SIMPLE_REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Assigning SIMPLE_BRANCH_NAME
        run: |
          BRANCH_NAME="${{ github.head_ref || github.ref_name}}"
          SIMPLE_BRANCH_NAME="${BRANCH_NAME//\//-}"
          echo "SIMPLE_BRANCH_NAME=${SIMPLE_BRANCH_NAME}" >> $GITHUB_ENV

      - name: Checkout badges branch dedicated to storing badges only
        uses: actions/checkout@v4
        with:
          ref: badges
          path: badges

      - name: Checkout Main Project
        uses: actions/checkout@v4
        with:
          path: main-project

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build with Gradle
        working-directory: main-project
        run: ./gradlew build spotbugsMain jacocoTestReport
        env:
          PROJECT_WORKFLOW: 'main-release'

      - name: Upload JaCoCo report artifact
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: main-project/build/reports/jacoco/test/html/

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2.11.0
        with:
          coverage-badge-filename: ${{ env.SIMPLE_BRANCH_NAME }}-coverage.svg
          badges-directory: badges
          jacoco-csv-file: main-project/build/reports/jacoco/test/jacocoTestReport.csv

      - name: Commit and Push the Badge
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Update JaCoCo coverage badge'
          add: '*.svg'
          pull: '--rebase --autostash'
          cwd: badges

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branches = ${{ steps.jacoco.outputs.branches }}"

      - name: Test Coverage Verification
        working-directory: main-project
        run: ./gradlew jacocoTestCoverageVerification
        env:
          PROJECT_WORKFLOW: 'main-pull-request'

      - name: Publish to GitHub Packages
        working-directory: main-project
        run: ./gradlew publishPlugins
        env:
          PROJECT_WORKFLOW: 'main-release'
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}

